string os_name                      # Operating system name
string os_version                   # Operating system version
string hostname                     # Name of the host machine

int64 mem_total_kb                  # Total system memory
CpuInfo cpu_info                    # CPU information
GpuInfo gpu_info                    # GPU information
Co2Info co2_info                    # CO2 information
